BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_train_w_ar_debug.yaml"
TRAINER_NAME: "ppo_e3b_hierarchical"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
VIDEO_OPTION: ["tensorboard"]
TENSORBOARD_DIR: "tb/foi/e3b_dbg"
VIDEO_DIR: "video_dir/foi/e3b_dbg"
TEST_EPISODE_COUNT: 10
EVAL_CKPT_PATH_DIR: ""
NUM_PROCESSES: 3 # 40
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints/foi/e3b_dbg"
PRELOAD_MAP: False
#T_MAX: 100
#T_EXP: 100
T_MAX: 20
T_EXP: 20
DISTRIBUTED: True

TOTAL_NUM_STEPS: -1
NUM_CHECKPOINTS: -1

NUM_UPDATES: 251
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 10

RL:
  PPO:
    # ppo params
    num_local_steps: 5
    num_global_steps: 4
    ppo_epoch: 4
    num_mini_batch: 1 # 10
    global_reward_type: 'impact'
    #global_reward_type: 'e3b'
    visitation_count: 'e3b'
    global_reward_scale: 0.01
  ANS:
    goal_interval: 5  # goal sampling interval for global policy
    use_ddp: True
    image_scale_hw: [128, 128]
    gpu_ids: [0]
    use_gt_positioning: False
    overall_map_size: 961 # gibson
    visitation_count_divider: 5
    obs_resized_dim: 42
    paper_encoder: True
    pretrained_paper_encoder: False
    pretrained_paper_encoder_weights: "pretrained_models/gibson-2plus-resnet50.pth"
    #pretrained_visual_encoder: True 
    CURIOSITY:
      use_normalized_advantage: False
      curiosity_hidden_size: 512
      #curiosity_hidden_size: 500
      use_curiosity_rnn: False
      #use_curiosity_rnn: True
      num_concat_obs: 1
      #num_concat_obs: 4
      update_epochs: 1
    MAPPER:
      map_size: 101
      map_batch_size: 32
      replay_size: 100 # very important otherwise it crasha
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      use_data_parallel: False
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'
      GP_ANTICIPATION:
        resnet_type: 'resnet18'
        unet_nsf: 16
    LOCAL_POLICY:
      use_heuristic_policy: False
