BASE_TASK_CONFIG_PATH: "configs/exploration/mp3d_evaluate_noise_free.yaml"
TRAINER_NAME: "ppo_e3b_hierarchical"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
#VIDEO_OPTION: ["disk"]
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/foi/e3b/mp3d_val"
VIDEO_DIR: "video_dir/e3b/mp3d_val"
TEST_EPISODE_COUNT: 2000
#TEST_EPISODE_COUNT: 5
EVAL_CKPT_PATH_DIR: "/homes/dborghi/projects/thesis_exploration2/data/new_checkpoints/foi/e3b_17/ckpt.25.pth"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
PRELOAD_MAP: False
T_MAX: 1000
T_EXP: 1000
SAVE_STATISTICS_FLAG: True

NUM_UPDATES: 10000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 100

NUM_CHECKPOINTS: -1
TOTAL_NUM_STEPS: -1
WRITER_TYPE: "tb"

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 10
    global_reward_type: 'impact'
    visitation_count: 'e3b'
    global_reward_scale: 0.01
  ANS:
    use_ddp: True
    image_scale_hw: [128, 128]
    gpu_ids: [0]
    use_gt_positioning: False
    overall_map_size: 2001 # mp3d
    visitation_count_divider: 5
    obs_resized_dim: 42
    paper_encoder: False
    pretrained_paper_encoder: False
    pretrained_paper_encoder_weights: "pretrained_models/gibson-2plus-resnet50.pth"
    CURIOSITY:
      use_normalized_advantage: False
      #curiosity_hidden_size: 512
      curiosity_hidden_size: 500
      use_curiosity_rnn: False
      #use_curiosity_rnn: True
      num_concat_obs: 1
      #num_concat_obs: 4
      update_epochs: 1
    MAPPER:
      map_size: 101
      map_batch_size: 32
      replay_size: 10000 # very important otherwise it crasha
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      use_data_parallel: False
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'
      GP_ANTICIPATION:
        resnet_type: 'resnet18'
        unet_nsf: 16
    LOCAL_POLICY:
      use_heuristic_policy: False

QUALITATIVE: False