BASE_TASK_CONFIG_PATH: "configs/exploration/mp3d_test_noise_free.yaml"
TRAINER_NAME: "ppo_occant_hierarchical"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
SIMULATOR_GPU_IDS: []
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/foi/occant_acc/mp3d_test"
VIDEO_DIR: "video_dir/foi/occant_acc/mp3d_test"
TEST_EPISODE_COUNT: 2000
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/foi/occant_acc/ckpt.25.pth"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
T_EXP: 1000
T_MAX: 1000
#DISTRIBUTED: True
SAVE_STATISTICS_FLAG: True

NUM_UPDATES: 10000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 100

NUM_CHECKPOINTS: -1
TOTAL_NUM_STEPS: -1
WRITER_TYPE: "tb"

EVAL:
  SPLIT: "test"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    #num_mini_batch: 1
    num_mini_batch: 10
    global_reward_type: 'impact'
    global_reward_scale: 0.01
  ANS:
    use_ddp: True
    image_scale_hw: [128, 128]
    gpu_ids: [0]
    reward_type: "map_accuracy"
    use_gt_positioning: False
    #crop_map_for_planning: False
    overall_map_size: 2001
    visitation_count_divider: 5
    obs_resized_dim: 42
    #    overall_map_size: 961
    #local_reward_type: 'diff'
    MAPPER:
      map_size: 101
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      ignore_pose_estimator: False  # <---
      map_batch_size: 32
      use_data_parallel: False
      replay_size: 10000
      gpu_ids: []
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'
      GP_ANTICIPATION:
        resnet_type: 'resnet18'
        unet_nsf: 16
    LOCAL_POLICY:
      use_heuristic_policy: False
    GLOBAL_POLICY:
      random_explorer: False

QUALITATIVE: False
